# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-12 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backends', '0005_auto_20180108_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('path_info', models.CharField(max_length=20)),
                ('real_path', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
